# http://travis-ci.org/#!/agschwender/pilbox
language: python
python:
  - 2.7
  - 3.2
env:
  - PYTHONPATH=$PYTHONPATH:$PWD
virtualenv:
    system_site_packages: true
before_install:
  - sudo apt-get install libjpeg8-dev libfreetype6-dev zlib1g-dev
  - sudo apt-get install libwebp-dev liblcms1-dev
  - sudo apt-get install python-numpy python-opencv
install:
  - pip install --use-mirrors tornado==3.1 Pillow==2.1.0 coveralls
  - pip install --use-mirrors pep8==1.4.6 pyflakes==0.7.3
before_script:
  - pep8 --exclude=test pilbox
  - pyflakes pilbox/*.py
script:
  - coverage run -m pilbox.test.runtests
after_success:
  - coveralls
